### ISSUE TITLE
How to generate release .zip file?

### ISSUE THREAD

**Issue by kakila** [dwengovzw/Ardublock-for-Dwenguino#1]
It isn't clear how to generate a release form this repository.
The local README's indicate that Maven should be used but the commands given there do not work, because the dependency with openblocks is not resolved properly.

Please extend the main README.md to explain how to make a release.

**Comment by suriyanath** [comment]
Hi I have updated the README.md and now you should be able to find the steps on how to generate ardublock-all.jar
